### PR TITLE
update belt icon to new Factorio version

### PR DESCRIPTION
**Pull request by atburghardt**
I updated the Belt pngs with my limited design skills :D .
Hope the quality is good enough.

### CODE REVIEW

**Comment by kirazy** [comment]
I appreciate you. <3

Been so distracted haven't been able to get myself to do this.

I'll take a look at your work.

**Comment by kirazy** [comment]
And done. <3

There's a few things I still want/need to do prior to releasing this but...
- [ ] Prismatic version + compatibility... though that's all handled by Prismatic belts.
- [ ] The "whatever I was calling the old-style version of the icon" mod support in compat.... though I suppose I hardly need to wait.

Release it is.

**Comment by KiwiHawk** [comment]
Can we add these directly to Bob's logistics?

**Comment by atburghardt** [comment]
> Can we add these directly to Bob's logistics?

Pullrequest created.
https://github.com/BobsMods/bobsmods/pull/73

**Comment by kirazy** [comment]
Bobs doesn't use hard coded icons anymore?

**Comment by kirazy** [comment]
Oh, it does. Of course.

**Pull request merged**
